# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: j1
    steps:
      - script: echo "J1"

  # This job should not run because the condition should evaluate to false
  - job: j2
    condition: eq('true', 'false')
    steps:
      - script: echo "j2"

  # This job should not run because it depends on j2 and j2 did not succeed as it was not run
  - job: j3
    dependsOn:
      - j1
      - j2
    condition: and(succeeded('j1'), succeeded('j2'))
    steps:
      - script: echo "j3"

  # This job should run as while it depends on j2, it only requires that j2 did not fail
  - job: j4
    dependsOn:
      - j1
      - j2
    condition: and(succeeded('j1'), not(failed('j2')))
    steps:
      - script: echo "j4"

  # This job should not run as it depends on j2 and j2 was not run
  - job: j5
    dependsOn:
      - j1
      - j2
    condition: succeeded()
    steps:
      - script: echo "j5"
